// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYY33xhgroGdTAPrOA_423ylu5irl-QxM',
    appId: '1:762167919122:web:0328dce075067ab0a7cecb',
    messagingSenderId: '762167919122',
    projectId: 'augrealdemo-76424',
    authDomain: 'augrealdemo-76424.firebaseapp.com',
    storageBucket: 'augrealdemo-76424.firebasestorage.app',
    measurementId: 'G-VSQ6RWZR2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-1WQzxqjdrkBvtv2nwXouquQ4-fhMX_g',
    appId: '1:762167919122:android:51cd7eec2152676ea7cecb',
    messagingSenderId: '762167919122',
    projectId: 'augrealdemo-76424',
    storageBucket: 'augrealdemo-76424.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ecrqHLX4EetEogDrbRP57OjwJoEKp9c',
    appId: '1:762167919122:ios:a03372025d0b0a5aa7cecb',
    messagingSenderId: '762167919122',
    projectId: 'augrealdemo-76424',
    storageBucket: 'augrealdemo-76424.firebasestorage.app',
    iosBundleId: 'com.example.augDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ecrqHLX4EetEogDrbRP57OjwJoEKp9c',
    appId: '1:762167919122:ios:a03372025d0b0a5aa7cecb',
    messagingSenderId: '762167919122',
    projectId: 'augrealdemo-76424',
    storageBucket: 'augrealdemo-76424.firebasestorage.app',
    iosBundleId: 'com.example.augDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYY33xhgroGdTAPrOA_423ylu5irl-QxM',
    appId: '1:762167919122:web:642908b995c8ea18a7cecb',
    messagingSenderId: '762167919122',
    projectId: 'augrealdemo-76424',
    authDomain: 'augrealdemo-76424.firebaseapp.com',
    storageBucket: 'augrealdemo-76424.firebasestorage.app',
    measurementId: 'G-FZGZ53NEHQ',
  );
}
